apiVersion: v1
kind: Service
metadata:
  name: node-dummy-with-db
spec:
  type: LoadBalancer
  selector:
    app: node-dummy-with-db
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
